#
#
version: '2'
services:
####
  ps-0:
    build: ./tf-worker/
    container_name: ps-0
    image: mesos-slave-15:5000/tensorflow-ps-0:0.1
    network_mode: "bridge"
    mem_limit: 80000m
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-32"
      - "POD_NAME:ps-0"

  ps-1:
    build: ./tf-worker/
    container_name: ps-1
    image: mesos-slave-15:5000/tensorflow-ps-1:0.1
    mem_limit: 80000m
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-31"
      - "POD_NAME:ps-1"

  ps-2:
    build: ./tf-worker/
    container_name: ps-2
    image: mesos-slave-15:5000/tensorflow-ps-2:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-30"
      - "POD_NAME:ps-2"

  ps-3:
    build: ./tf-worker/
    container_name: ps-3
    image: mesos-slave-15:5000/tensorflow-ps-3:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-29"
      - "POD_NAME:ps-3"
####
  worker-0:
    build: ./tf-worker/
    container_name: worker-0
    image: mesos-slave-15:5000/tensorflow-worker-0:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-01"
      - "POD_NAME:worker-0"

  worker-1:
    build: ./tf-worker/
    container_name: worker-1
    image: mesos-slave-15:5000/tensorflow-worker-1:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-02"
      - "POD_NAME:worker-1"

  worker-2:
    build: ./tf-worker/
    container_name: worker-2
    image: mesos-slave-15:5000/tensorflow-worker-2:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-03"
      - "POD_NAME:worker-2"

  worker-3:
    build: ./tf-worker/
    container_name: worker-3
    image: mesos-slave-15:5000/tensorflow-worker-3:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-04"
      - "POD_NAME:worker-3"

  worker-4:
    build: ./tf-worker/
    container_name: worker-4
    image: mesos-slave-15:5000/tensorflow-worker-4:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-05"
      - "POD_NAME:worker-4"

  worker-5:
    build: ./tf-worker/
    container_name: worker-5
    image: mesos-slave-15:5000/tensorflow-worker-5:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-06"
      - "POD_NAME:worker-5"

  worker-6:
    build: ./tf-worker/
    container_name: worker-6
    image: mesos-slave-15:5000/tensorflow-worker-6:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-07"
      - "POD_NAME:worker-6"

  worker-7:
    build: ./tf-worker/
    container_name: worker-7
    image: mesos-slave-15:5000/tensorflow-worker-7:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-08"
      - "POD_NAME:worker-7"

  worker-8:
    build: ./tf-worker/
    container_name: worker-8
    image: mesos-slave-15:5000/tensorflow-worker-8:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-09"
      - "POD_NAME:worker-8"

  worker-9:
    build: ./tf-worker/
    container_name: worker-9
    image: mesos-slave-15:5000/tensorflow-worker-9:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-10"
      - "POD_NAME:worker-9"

  worker-10:
    build: ./tf-worker/
    container_name: worker-10
    image: mesos-slave-15:5000/tensorflow-worker-10:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-11"
      - "POD_NAME:worker-10"

  worker-11:
    build: ./tf-worker/
    container_name: worker-11
    image: mesos-slave-15:5000/tensorflow-worker-11:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-12"
      - "POD_NAME:worker-11"

  worker-12:
    build: ./tf-worker/
    container_name: worker-12
    image: mesos-slave-15:5000/tensorflow-worker-12:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-13"
      - "POD_NAME:worker-12"

  worker-13:
    build: ./tf-worker/
    container_name: worker-13
    image: mesos-slave-15:5000/tensorflow-worker-13:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-14"
      - "POD_NAME:worker-13"

  worker-14:
    build: ./tf-worker/
    container_name: worker-14
    image: mesos-slave-15:5000/tensorflow-worker-14:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-16"
      - "POD_NAME:worker-14"

  worker-15:
    build: ./tf-worker/
    container_name: worker-15
    image: mesos-slave-15:5000/tensorflow-worker-15:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-17"
      - "POD_NAME:worker-15"

  worker-16:
    build: ./tf-worker/
    container_name: worker-16
    image: mesos-slave-15:5000/tensorflow-worker-16:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-18"
      - "POD_NAME:worker-16"

  worker-17:
    build: ./tf-worker/
    container_name: worker-17
    image: mesos-slave-15:5000/tensorflow-worker-17:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-19"
      - "POD_NAME:worker-17"

  worker-18:
    build: ./tf-worker/
    container_name: worker-18
    image: mesos-slave-15:5000/tensorflow-worker-18:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-20"
      - "POD_NAME:worker-18"

  worker-19:
    build: ./tf-worker/
    container_name: worker-19
    image: mesos-slave-15:5000/tensorflow-worker-19:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-21"
      - "POD_NAME:worker-19"

  worker-20:
    build: ./tf-worker/
    container_name: worker-20
    image: mesos-slave-15:5000/tensorflow-worker-20:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-22"
      - "POD_NAME:worker-20"

  worker-21:
    build: ./tf-worker/
    container_name: worker-21
    image: mesos-slave-15:5000/tensorflow-worker-21:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-23"
      - "POD_NAME:worker-21"

  worker-22:
    build: ./tf-worker/
    container_name: worker-22
    image: mesos-slave-15:5000/tensorflow-worker-22:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-24"
      - "POD_NAME:worker-22"

  worker-23:
    build: ./tf-worker/
    container_name: worker-23
    image: mesos-slave-15:5000/tensorflow-worker-23:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-25"
      - "POD_NAME:worker-23"

  worker-24:
    build: ./tf-worker/
    container_name: worker-24
    image: mesos-slave-15:5000/tensorflow-worker-24:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-26"
      - "POD_NAME:worker-24"

  worker-25:
    build: ./tf-worker/
    container_name: worker-25
    image: mesos-slave-15:5000/tensorflow-worker-25:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-27"
      - "POD_NAME:worker-25"

  worker-26:
    build: ./tf-worker/
    container_name: worker-26
    image: mesos-slave-15:5000/tensorflow-worker-26:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-28"
      - "POD_NAME:worker-26"
####
  master-0:
    build: ./tf-worker/
    container_name: master-0
    image: mesos-slave-15:5000/tensorflow-master-0:0.1
    network_mode: "bridge"
    ports:
      - "8080"
    environment:
      - "constraint:node==mesos-slave-15"
      - "POD_NAME:master-0"

####
  jupyter-server:
    build:
      context: ./tf-jupyter/
    container_name: tf-jupyter-server
    image: mesos-slave-15:5000/tensorflow-jupyter-server:0.1
    network_mode: "bridge"
#    networks:
#      - swarm-cluster
    ports:
      - "8888:8888"
      - "80:80"
    volumes:
      - /opt/hdfs/logs/tensorflow-logs:/var/log/tensorflow
####
  tf-tensorboard-server:
    image: mesos-slave-15:5000/tensorflow
#    networks:
#      - swarm-cluster
    network_mode: "bridge"
    container_name: tf-tensorboard-server
    ports:
      - "6006:6006"
    links:
      - jupyter-server
      - master-0
    command: /tensorflow/bazel-bin/tensorflow/tensorboard/tensorboard --logdir=/var/log/tensorflow
    volumes:
      - /opt/hdfs/logs/tensorflow-logs:/var/log/tensorflow
#networks:
#  swarm-cluster:
#    driver: overlay
